# Generated by Django 6.1.1 on 2026-09-09 20:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'TokenBlacklist',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('replaced_by', models.CharField(blank=True, max_length=255, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'RefreshToken',
                'indexes': [models.Index(fields=['expires_at'], name='idx_refreshtoken_expires_at')],
            },
        ),
    ]
